@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mastermarisa.maid_restaurant.maid.behavior.chef;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;