@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.mastermarisa.maid_restaurant.task.api;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;