@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mastermarisa.maid_restaurant.task.cooker;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;