@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.mastermarisa.maid_restaurant.datagen.tag;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;